server:
  port: 9092

spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql-container:3306/bank
    username: root
    password: springbankNet

security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey
axon:
  axonserver:
    servers: axon-server
